version: 1
default_environment: dev
project_id: 70d9670f-9691-400e-aaf2-49a378faa6d2

environments:
- name: dev
- name: staging
- name: prod

plugins:
  extractors:
  - name: tap-rest-api-msdk
    variant: widen
    pip_url: tap-rest-api-msdk
    config:
      api_url: https://api.yuman.io
      auth_method: bearer_token
      bearer_token: ${YUMAN_BEARER_TOKEN}
      request_timeout: 300
      request_records_limit: 1000
      backoff_type: header
      backoff_time_extension: 15
      streams:
      - name: yuman_sites
        path: /v1/sites
        records_path: $.items[*]
        primary_keys: [id]
        replication_key: updated_at
        paginator: page_number_paginator
        pagination_page_size: 50
        pagination_initial_offset: 1
        pagination_limit_per_page_param: per_page
        pagination_page_number_field: page
        # SUPPRIMEZ cette ligne - elle n'est pas nécessaire pour page_number_paginator
        # next_page_token_path: $.page
        # AJOUTEZ cette ligne pour définir la condition d'arrêt
        pagination_total_limit_param: total_pages
        params:
          per_page: 50
          embed: fields


  loaders:
  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
    config:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}
      default_target_schema: ${POSTGRES_SCHEMA}
      validate_records: false
      batch_config:
        encoding:
          format: jsonl
          compression: gzip
        batch_size: 50000
      max_batch_age: 600
      batch_size_rows: 30000
      flush_all_streams: true
      add_record_metadata: true
      hard_delete: false


  utilities:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core dbt-postgres meltano-dbt-ext~=0.3.0
    config:
      host: echo.evs-pro.fr
      port: 31415
      user: echo
      dbname: echo
      schema: analytics