# staging/yuman_api/schema.yml
version: 2

models:
  - name: stg_yuman_api__clients
    description: "Clients transformés et nettoyés depuis l'API Yuman"
    columns:
      - name: client_id
        description: "Identifiant unique du client"
        tests:
          - unique
          - not_null

  - name: stg_yuman_api__sites
    description: "Sites transformés et nettoyés depuis l'API Yuman"
    columns:
      - name: site_id
        description: "Identifiant unique du site"
        tests:
          - unique
          - not_null
      - name: client_id
        description: "Référence vers le client propriétaire"
        tests:
          - not_null
          - relationships:
              to: ref('stg_yuman_api__clients')
              field: client_id

  - name: stg_yuman_api__materials
    description: "Matériaux transformés et nettoyés depuis l'API Yuman"
    columns:
      - name: material_id
        description: "Identifiant unique du matériau"
        tests:
          - unique
          - not_null
      - name: site_id
        description: "Référence vers le site propriétaire"
        tests:
          - not_null
          - relationships:
              to: ref('stg_yuman_api__sites')
              field: site_id